# Generated by Django 4.1.5 on 2023-02-07 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=datetime.date.today, max_length=255, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default=datetime.date.today, max_length=255, verbose_name='نام خانوادگی'),
            preserve_default=False,
        ),
    ]
