# Generated by Django 4.1.5 on 2023-02-07 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_name_user_surname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name_fa',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='surname',
            new_name='last_name_fa',
        ),
    ]
