# Generated by Django 4.1.4 on 2022-12-28 18:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام بخش')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام بیمه')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نوع خدمت')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام خدمت')),
                ('cost', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='( ریال ) هزینه')),
                ('duration', models.DurationField(default=None, verbose_name='مدت زمان')),
                ('active', models.BooleanField(verbose_name='فعال')),
                ('ServiceTypeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service', to='yasha.servicetype', verbose_name='نوع خدمت')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service', to='yasha.department', verbose_name='نام بخش')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='نام')),
                ('last_name', models.CharField(max_length=150, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(max_length=150, verbose_name='نام پدر')),
                ('identity', models.CharField(max_length=20, unique=True, verbose_name='کد ملی')),
                ('phone', models.CharField(max_length=255, verbose_name='تلفن')),
                ('mobile', models.CharField(max_length=255, verbose_name='موبایل')),
                ('date_joined', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ پذیرش بیمار')),
                ('birth_date', models.DateField(verbose_name='تاریخ تولد')),
                ('guardian', models.CharField(max_length=20, verbose_name='کد ملی سرپرست بیمار')),
                ('referrer', models.CharField(choices=[('Person', 'شخص'), ('Instagram', 'اینستاگرام'), ('Internet', 'اینترنت'), ('Tract', 'تراکت'), ('Organization', 'سازمان')], default='Organization', max_length=20, verbose_name='معرف')),
                ('gender', models.CharField(choices=[('man', 'مرد'), ('woman', 'زن'), ('other', 'سایر')], default='woman', max_length=20, verbose_name='جنسیت')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='ایمیل')),
                ('start_date_insurance', models.DateField(verbose_name='تاریخ شروع بیمه')),
                ('end_date_insurance', models.DateField(verbose_name='تاریخ پایان بیمه')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient', to='yasha.insurance', verbose_name='نام بیمه')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=20, unique=True, verbose_name='کد ملی')),
                ('professionalStatement', models.CharField(max_length=255, null=True, verbose_name='تخصص')),
                ('phone', models.CharField(max_length=255, verbose_name='تلفن')),
                ('mobile', models.CharField(max_length=255, verbose_name='موبایل')),
                ('gender', models.CharField(choices=[('man', 'مرد'), ('woman', 'زن'), ('other', 'سایر')], default='woman', max_length=20, verbose_name='جنسیت')),
                ('Contract', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='درصد قرارداد')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
