# Generated by Django 4.1.4 on 2022-12-28 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yasha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'بخش'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name_plural': 'پزشکان'},
        ),
        migrations.AlterModelOptions(
            name='insurance',
            options={'verbose_name_plural': 'بیمه'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name_plural': 'بیماران'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['id'], 'verbose_name_plural': 'خدمات'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'ordering': ['id'], 'verbose_name_plural': 'نوع خدمت'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
