# Generated by Django 4.1.4 on 2022-12-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0002_alter_department_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
