# Generated by Django 4.1.4 on 2022-12-30 11:45

from django.db import migrations, models
import django.db.models.deletion
import yasha.validators


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0003_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'نظر بیماران'},
        ),
        migrations.CreateModel(
            name='DoctorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='yasha/images/doctor', validators=[yasha.validators.validate_file_size])),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='yasha.doctor')),
            ],
        ),
    ]
