# Generated by Django 4.1.4 on 2022-12-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0004_alter_review_options_doctorimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('phone1', models.CharField(max_length=255, verbose_name='خط تلفن 1')),
                ('phone2', models.CharField(max_length=255, null=True, verbose_name='خط تلفن 2')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='ایمیل')),
                ('linkedin', models.CharField(max_length=255, verbose_name='لینکدین')),
                ('instagram', models.CharField(max_length=255, verbose_name='اینستاگرام')),
                ('whatsapp', models.CharField(max_length=255, verbose_name='واتس اپ')),
            ],
        ),
    ]
