# Generated by Django 4.1.4 on 2023-01-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0005_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'درباره ما'},
        ),
        migrations.AddField(
            model_name='about',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
