# Generated by Django 4.1.4 on 2023-01-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0006_alter_about_options_about_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={},
        ),
        migrations.AlterField(
            model_name='about',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
    ]
