# Generated by Django 4.1.4 on 2023-01-01 16:27

from django.db import migrations, models
import django.db.models.deletion
import yasha.validators


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0007_alter_about_options_alter_about_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'درباره ما'},
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='yasha/images/service', validators=[yasha.validators.validate_file_size])),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='yasha.service')),
            ],
        ),
    ]
