# Generated by Django 4.1.4 on 2023-01-01 16:33

from django.db import migrations, models
import django.db.models.deletion
import yasha.validators


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0008_alter_about_options_serviceimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTypeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='yasha/images/servicetype', validators=[yasha.validators.validate_file_size])),
                ('ServiceType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='yasha.servicetype')),
            ],
        ),
        migrations.DeleteModel(
            name='ServiceImage',
        ),
    ]
