# Generated by Django 4.1.4 on 2023-01-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0009_servicetypeimage_delete_serviceimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('your_problem', models.CharField(max_length=255, verbose_name='مشکل بیمار')),
                ('phone', models.CharField(max_length=255, verbose_name='تلفن')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت درخواست')),
            ],
        ),
    ]
