# Generated by Django 4.1.4 on 2023-01-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0010_appointmentrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentrequest',
            options={'verbose_name_plural': 'درخواست وقت ویزیت بیمار'},
        ),
    ]
