# Generated by Django 4.1.4 on 2023-01-04 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0011_alter_appointmentrequest_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='ServiceTypeID',
            new_name='servicetype',
        ),
    ]
