# Generated by Django 4.1.4 on 2023-01-04 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0012_rename_servicetypeid_service_servicetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='address',
        ),
        migrations.AddField(
            model_name='about',
            name='city',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='شهر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='country',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='کشور'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='flat',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='پلاک'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='street',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='خیابان'),
            preserve_default=False,
        ),
    ]
