# Generated by Django 4.1.4 on 2023-01-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0013_remove_about_address_about_city_about_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='city',
            field=models.CharField(max_length=255, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='about',
            name='country',
            field=models.CharField(max_length=255, verbose_name='کشور'),
        ),
        migrations.AlterField(
            model_name='about',
            name='flat',
            field=models.CharField(max_length=255, verbose_name='پلاک'),
        ),
        migrations.AlterField(
            model_name='about',
            name='street',
            field=models.CharField(max_length=255, verbose_name='خیابان'),
        ),
    ]
