# Generated by Django 4.1.4 on 2023-01-07 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0014_alter_about_city_alter_about_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicetype',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات'),
        ),
    ]
