# Generated by Django 4.1.4 on 2023-01-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0015_servicetype_date_servicetype_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='date',
        ),
        migrations.AddField(
            model_name='servicetype',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
