# Generated by Django 4.1.4 on 2023-01-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0016_remove_servicetype_date_servicetype_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
    ]
