# Generated by Django 4.1.4 on 2023-01-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0017_alter_servicetype_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
