# Generated by Django 4.1.4 on 2023-01-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0018_alter_servicetype_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'سوالات',
            },
        ),
    ]
