# Generated by Django 4.1.4 on 2023-01-10 09:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import yasha.validators


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0019_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='yasha/images/clinic', validators=[yasha.validators.validate_file_size])),
                ('video', models.FileField(null=True, upload_to='yasha/images/clinic', validators=[yasha.validators.validate_video_size, django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='yasha.about')),
            ],
        ),
    ]
