# Generated by Django 4.1.4 on 2023-01-10 11:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import yasha.validators


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0020_clinicsight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='yasha/images/clinic', validators=[yasha.validators.validate_file_size], verbose_name='عکس')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='yasha.about', verbose_name='درباره')),
            ],
            options={
                'verbose_name_plural': 'تصاویر کلینیک',
            },
        ),
        migrations.CreateModel(
            name='ClinicVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('video', models.FileField(null=True, upload_to='yasha/images/clinic', validators=[yasha.validators.validate_video_size, django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='فیلم')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='yasha.about', verbose_name='درباره')),
            ],
            options={
                'verbose_name_plural': 'ویدئوهای کلینیک',
            },
        ),
        migrations.DeleteModel(
            name='ClinicSight',
        ),
    ]
