# Generated by Django 4.1.5 on 2023-01-15 22:36

import django.core.validators
from django.db import migrations, models
import yasha.validators


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0021_clinicimage_clinicvideo_delete_clinicsight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorimage',
            options={'verbose_name_plural': 'تصاویر پزشک'},
        ),
        migrations.AlterModelOptions(
            name='servicetypeimage',
            options={'verbose_name_plural': 'تصاویر سرویس'},
        ),
        migrations.AlterField(
            model_name='clinicvideo',
            name='video',
            field=models.FileField(null=True, upload_to='yasha/images/clinic', validators=[yasha.validators.validate_video_size, django.core.validators.FileExtensionValidator(allowed_extensions=['mov', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='فیلم'),
        ),
    ]
