# Generated by Django 4.1.5 on 2023-01-16 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0022_alter_doctorimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicvideo',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='yasha.about', verbose_name='درباره'),
        ),
    ]
