# Generated by Django 4.1.5 on 2023-02-07 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0023_alter_clinicvideo_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentrequest',
            options={'verbose_name_plural': 'درخواست وقت'},
        ),
    ]
