# Generated by Django 4.1.5 on 2023-02-07 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0024_alter_appointmentrequest_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance',
            old_name='name',
            new_name='name_fa',
        ),
        migrations.AddField(
            model_name='insurance',
            name='description_en',
            field=models.TextField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurance',
            name='description_fa',
            field=models.TextField(default=datetime.date.today, verbose_name='توضیحات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurance',
            name='name_en',
            field=models.CharField(default=datetime.date.today, max_length=150),
            preserve_default=False,
        ),
    ]
