# Generated by Django 4.1.5 on 2023-02-08 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0025_rename_name_insurance_name_fa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='city',
            new_name='city_fa',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='country',
            new_name='country_fa',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='description',
            new_name='description_fa',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='flat',
            new_name='flat_fa',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='street',
            new_name='street_fa',
        ),
        migrations.AddField(
            model_name='about',
            name='city_en',
            field=models.CharField(default=datetime.date.today, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='country_en',
            field=models.CharField(default=datetime.date.today, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='description_en',
            field=models.TextField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='flat_en',
            field=models.CharField(default=datetime.date.today, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='street_en',
            field=models.CharField(default=datetime.date.today, max_length=255),
            preserve_default=False,
        ),
    ]
