# Generated by Django 4.1.5 on 2023-02-08 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0026_rename_city_about_city_fa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetype',
            options={'ordering': ['name_fa'], 'verbose_name_plural': 'نوع خدمت'},
        ),
        migrations.RenameField(
            model_name='servicetype',
            old_name='description',
            new_name='description_fa',
        ),
        migrations.RenameField(
            model_name='servicetype',
            old_name='name',
            new_name='name_fa',
        ),
        migrations.AddField(
            model_name='servicetype',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='name_en',
            field=models.CharField(default=datetime.date.today, max_length=150),
            preserve_default=False,
        ),
    ]
