# Generated by Django 4.1.5 on 2023-02-08 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0027_alter_servicetype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='description_en',
            field=models.TextField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='description_fa',
            field=models.TextField(default=datetime.date.today, verbose_name='توضیحات'),
            preserve_default=False,
        ),
    ]
