# Generated by Django 4.1.5 on 2023-02-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0028_alter_servicetype_description_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['user__last_name_fa'], 'verbose_name_plural': 'پزشکان'},
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='professionalStatement',
            new_name='professionalStatement_en',
        ),
        migrations.AddField(
            model_name='doctor',
            name='professionalStatement_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='تخصص'),
        ),
    ]
