# Generated by Django 4.1.5 on 2023-02-08 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0029_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='professionalStatement_en',
            field=models.CharField(default=datetime.date.today, max_length=255, verbose_name='تخصص'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='professionalStatement_fa',
            field=models.CharField(default=datetime.date.today, max_length=255, verbose_name='تخصص'),
            preserve_default=False,
        ),
    ]
