# Generated by Django 4.1.5 on 2023-02-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0030_alter_doctor_professionalstatement_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='professionalStatement_en',
            field=models.CharField(max_length=255),
        ),
    ]
