# Generated by Django 4.1.5 on 2023-02-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0031_alter_doctor_professionalstatement_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='ایمیل'),
        ),
    ]
