# Generated by Django 4.1.5 on 2023-02-08 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0032_alter_about_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='question',
            new_name='question_en',
        ),
        migrations.AddField(
            model_name='questions',
            name='description_fa',
            field=models.TextField(default=datetime.date.today, verbose_name='توضیحات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='question_fa',
            field=models.TextField(default=datetime.date.today, verbose_name='سوال'),
            preserve_default=False,
        ),
    ]
