# Generated by Django 4.1.5 on 2023-02-10 15:51

from django.db import migrations, models
import django.db.models.deletion
import yasha.validators


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0033_rename_description_questions_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=150, verbose_name='دسته بندی')),
                ('name_en', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'دسته بندی سوالات',
            },
        ),
        migrations.CreateModel(
            name='DoctorPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_before', models.ImageField(upload_to='yasha/images/portfolio', validators=[yasha.validators.validate_file_size], verbose_name='عکس قبل')),
                ('image_after', models.ImageField(upload_to='yasha/images/portfolio', validators=[yasha.validators.validate_file_size], verbose_name='عکس بعد')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='yasha.doctor')),
            ],
            options={
                'verbose_name_plural': 'نمونه کارها',
            },
        ),
    ]
