# Generated by Django 4.1.5 on 2023-02-10 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0034_category_doctorportfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorportfolio',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='doctorportfolio',
            name='title_fa',
            field=models.CharField(default=1, max_length=255, verbose_name='عنوان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name_fa',
            field=models.CharField(max_length=150, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='doctorportfolio',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='yasha.doctor', verbose_name='نام پزشک'),
        ),
    ]
