# Generated by Django 4.1.5 on 2023-02-11 22:57

from django.db import migrations, models
import yasha.validators


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0035_rename_title_doctorportfolio_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='workingـhours_en',
            field=models.CharField(default='1', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='workingـhours_fa',
            field=models.CharField(default='1', max_length=500, verbose_name='ساعات کاری'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorportfolio',
            name='image_after',
            field=models.ImageField(upload_to='yasha/images/portfolio', validators=[yasha.validators.validate_file_size], verbose_name='آپلود عکس بعد'),
        ),
        migrations.AlterField(
            model_name='doctorportfolio',
            name='image_before',
            field=models.ImageField(upload_to='yasha/images/portfolio', validators=[yasha.validators.validate_file_size], verbose_name='آپلود عکس قبل'),
        ),
    ]
