# Generated by Django 4.1.5 on 2023-02-12 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import yasha.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yasha', '0036_about_workingـhours_en_about_workingـhours_fa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colleague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professionalStatement_fa', models.CharField(max_length=255, verbose_name='تخصص')),
                ('professionalStatement_en', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name_plural': 'همکاران',
                'ordering': ['user__last_name_fa'],
            },
        ),
        migrations.CreateModel(
            name='ColleagueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='yasha/images/colleague', validators=[yasha.validators.validate_file_size])),
                ('colleague', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='yasha.colleague')),
            ],
            options={
                'verbose_name_plural': 'تصویر همکار',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
