# Generated by Django 4.1.5 on 2023-02-13 11:17

from django.db import migrations, models
import yasha.validators


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0037_colleague_colleagueimage_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='image',
            field=models.ImageField(default='1', upload_to='yasha/images/Insurance', validators=[yasha.validators.validate_file_size]),
            preserve_default=False,
        ),
    ]
