# Generated by Django 4.1.5 on 2023-02-13 15:37

from django.db import migrations, models
import yasha.validators


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0038_insurance_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='telegram',
            field=models.CharField(default='1', max_length=255, verbose_name='تلگرام'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insurance',
            name='image',
            field=models.ImageField(upload_to='yasha/images/Insurance', validators=[yasha.validators.validate_file_size], verbose_name='لوگو'),
        ),
    ]
