# Generated by Django 4.1.5 on 2023-02-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasha', '0039_about_telegram_alter_insurance_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='email',
            field=models.EmailField(default='1@gmail.com', max_length=254, verbose_name='ایمیل'),
            preserve_default=False,
        ),
    ]
